### ISSUE TITLE
Feature Request: Support for LanguageTool Premium account

### ISSUE THREAD

**Issue by drunktankpink** [tito21/joplin-langugetool#3]
A feature for a later version, but it would be good to have the option of using the Premium API and passing the account and API key.

> If you have a LanguageTool Premium account, copy and paste https://api.languagetoolplus.com/v2 in “Base URL,” write your email address, and type in the API key

**Comment by tito21** [comment]
I was planing to implement this feature and is now ready on version 0.0.10.

In other note, how did you install the plugin? In my computer only works properly when installed in developer mode, see #1. I want to know if this is problem is on my setup, or it is in the plugin itself.

Thanks for being interested in my plugin.

**Comment by drunktankpink** [comment]
I have this installed on the production version on both Mac and Windows. 
Can you explain a bit more what you mean by “the items are not loaded in the context menu”?

For me, I can see the errors and get suggestions if I right-click. I do have a small issue where if I set a language, then it doesn't work. But I can raise another issue for that after I have played around a bit more.

**Comment by tito21** [comment]
Thanks for the information. For me (Windows 11) on the production version (from the official repo), the text does get marked, but the suggestion doesn't appear in the context menu. However, the plugin does work when installed from the advanced settings.

For setting the language, you can open another issue for that. The language has to be specified with a language code.
